basic/controllers/RotasController.php
<?php

namespace app\controllers;

use app\models\Fotos;
use Yii;
use app\models\Rota;
use app\models\RotaSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RotasController implements the CRUD actions for Rota model.
 */
class RotasController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'except'=>['ver','index'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ]
                    // everything else is denied
                ],
            ],

        ];
    }


    /**
     * Lists all Rota models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RotaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionNova(){
        return $this->addEdit();
    }

    public function actionAltera(){
        return $this->addEdit();
    }


    private function addEdit()
    {
        $id=Yii::$app->request->get('id');
        if($this->action->id=='nova' && !empty($id))
            return $this->redirect(array_merge(['rotas/altera'],Yii::$app->request->get()));
        if($this->action->id=='altera' && empty($id))
            return $this->redirect('nova');

        $this->css=[
            "/css/jquery.fileupload.css",
            "/css/jquery.fileupload-ui.css",
            "/css/ng-ckeditor.css",
        ];

        $this->javaScript=[
            "/js/html2canvas.js",
            "/js/vendor/jquery.ui.widget.js",
            "//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js",
            "//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js",
            "//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js",
            "//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js",
            "//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js",
            "/js/jquery.iframe-transport.js",
            "/js/jquery.fileupload.js",
            "/js/jquery.fileupload-process.js",
            "/js/jquery.fileupload-image.js",
            "/js/jquery.fileupload-video.js",
            "/js/jquery.fileupload-validate.js",
            "/js/jquery.fileupload-angular.js",
            "/js/ckeditor/ckeditor.js",
            "/js/ng-ckeditor.js",
            "/js/routemap.js",
            "/js/leftPanel.js",
            "/js/resizeMap.js",
            "/js/app.js",
            ];


        $foto = new Fotos();
        return $this->render('rota',['foto'=>$foto]);
    }

    /**
     * Displays a single Rota model.
     * @param string $id
     * @return mixed
     */
    public function actionVer($id)
    {
        $id=Yii::$app->request->get('id');
        if($this->action->id=='nova' && !empty($id))
            return $this->redirect(array_merge(['rotas/altera'],Yii::$app->request->get()));
        if($this->action->id=='altera' && empty($id))
            return $this->redirect('nova');

        $this->javaScript=[
            "/js/flexslider/jquery.flexslider.js",
    //        "/js/ng-flexslider/angular-flexslider.js",
//            "/js/jssor.slider.mini.js",
            "/js/routemap.js",
            "/js/resizeMap.js",
            "/js/app2.js",
        ];

        $this->css=["/js/flexslider/flexslider.css"];

        $foto = new Fotos();
        return $this->render('view',['foto'=>$foto]);
    }


    /**
     * @return mixed
     */
    public function actionTest()
    {
        $this->javaScript=[
            "/js/ng-ckeditor.js",
            "/js/verrota.js",
            "/js/leftPanel.js",
            "/js/resizeMap.js"
        ];

        $this->css=[
        ];
        return $this->render('test');

    }

    public function beforeAction($event)
    {
        return parent::beforeAction($event);
    }

    /**
     * Finds the Rota model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Rota the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rota::find()->joinWith(['pontos','pontos.fotos'])->where(['rota.id'=>$id])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= "utf-8"//Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>


    <?php //<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true"></script> ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/angular.js"></script>

    <script rel="stylesheet" src="/css/lobibox.css"></script>




    <script type="text/javascript" src="/js/gmaps.js"></script>
    <script type="text/javascript" src="/js/rainbowvis.js"></script>
    <script type="text/javascript" src="/js/lobibox.js"></script>


    <link href='//fonts.googleapis.com/css?family=Convergence|Bitter|Droid+Sans|Ubuntu+Mono' rel='stylesheet' type='text/css' />


    <?php
    if(!empty(Yii::$app->controller->css)) :
        if(!is_array(Yii::$app->controller->css))
            Yii::$app->controller->css=[Yii::$app->controller->css];
            foreach(Yii::$app->controller->css as $cssFile) :
    ?>
                <link href='<?= $cssFile ?>' rel='stylesheet' type='text/css' />
    <?php
            endforeach;
        endif;
    ?>

    <?php
    if(!empty(Yii::$app->controller->javaScript)) :
        if(!is_array(Yii::$app->controller->javaScript))
            Yii::$app->controller->javaScript=[Yii::$app->controller->javaScript];
        foreach(Yii::$app->controller->javaScript as $javaScriptFile) :
            ?>
            <script type="text/javascript" src="<?= $javaScriptFile ?>"></script>
    <?php
        endforeach;
    endif;
    ?>
    <link href='/css/site.css' rel='stylesheet' type='text/css' />
    <link href='/css/styles.css' rel='stylesheet' type='text/css' />
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?libraries=places&language=pt&region=pt&callback=initMap" async defer></script>
    <script  type="text/javascript">
        var tryModule = function(name) {

            // attempt to load the module into m
            var m;
            try {
                m = angular.module(name)
            } catch(err) {
                m = angular.module(name,[]);
            }

            // if it could not be loaded, try the rest of
            // the options. if it was, return it.
            return m;
        };

    </script>

</head>
<body ng-app="routeApp">
<?php $this->beginBody() ?>
<div class="wrap clearfix">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::t('app','Rotas'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    if(! Yii::$app->user->isGuest)
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-left ',
                          'ng-controller'=>'rotasController'],
            'items' => [
                ['label' => 'Nova rota', 'url' => '/rotas/nova'],
                [
                    'label' => 'Minhas Rotas',
                    'url'   => '#',
                    'items' => [
                        //'<li class="divider"></li>',
                        '<li data-ng-repeat="myroute in rotas">
                            <a ng-click="loadroute(myroute)" href="#">{{myroute.descricao}}</a> </li>',
                    ],
                ],


            ]
        ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => Yii::t('app','Sobre'), 'url' => ['/site/about']],
            //['label' => Yii::t('app','Contacto'), 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Entrar', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    Yii::t('app','Sair').' (' . Yii::$app->user->identity->nome . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Portugal Rotas <?= date('Y') ?></p>

        <?php include "share.php" ?>
    </div>
</footer>

<?php yii\web\View::clear() ?>
<?php $this->endBody() ?>
<script type="text/javascript">
    (function () {
        // handle bug on yii menu for small screens
        //<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w0-collapse" aria-expanded="true"><span class="sr-only">Toggle
        $('button[data-toggle=collapse]').click(function(e) {
            var target = $(this).data('target');
            if( $(target).hasClass('in') ) {
                $(target).removeClass('in',{duration:500});
                return false;
            }
        });


        tryModule('routeApp').controller('rotasController',
            ['$rootScope','$scope','$http','$location',
                function($rootScope,$scope,$http,$location){

                    $scope.load=function( callback ) {
                        $http.get("/rota/list").
                            success(function (data) {
                                if (data.message != 'ok') {
                                    if (typeof(data.message) == 'string')
                                        data.message = [data.message];
                                    jQuery.each(data.message, function (i, mess) {
                                        Lobibox.notify('error', {
                                            msg: mess,
                                            sound: false,
                                            delay: 2000,
                                            size: 'mini'
                                        });
                                    });
                                } else {
                                    if (typeof(callback) == "function")
                                        callback(data);
                                    $scope.rotas=data.data;
                                }
                            }).error(function (jqXHR, textStatus, error) {
                                Lobibox.notify('error', {
                                    msg: error,
                                    sound: false,
                                    delay: 2000,
                                    size: 'mini'
                                });
                            });
                    }

                    $rootScope.$on('loadRotas',function(){
                        $scope.load();
                    })

                    $scope.loadroute=function(rota){
                        window.location.href = '/rotas/altera?id='+rota.id;
                    }

                    $scope.rotas=[];
                    $rootScope.$emit('loadRotas');
                }]);


    }());

</script>

</body>
</html>
<?php $this->endPage() ?>